/**
 * Which names the glossary defines — the keys, without the definitions
 * (PLAN.md M116).
 *
 * **Generated. Run `node scripts/glossaryTerms.mjs` after editing
 * `content/glossary.ts`;** `glossary.test.ts` fails if this is stale.
 *
 * ## Why it exists
 *
 * `<Term>` renders an exercise name as a tappable definition when the
 * glossary has one and as ordinary text when it does not, so it has to
 * answer *"is this a term?"* before anything is tapped. It answered that by
 * importing the whole glossary — **13.99KB gzipped of definitions to decide
 * whether to underline a word**, on three lazy pages including the logger,
 * measured on M115's twenty-chunk fan-out.
 *
 * The keys are 1.7KB of that. They live here; the definitions load on the
 * tap that asks for one.
 *
 * Normalisation lives here too, rather than beside the entries, so the
 * question and the answer cannot disagree about what counts as the same
 * word.
 */

/** Normalised lookup key: exact term, case and surrounding space aside. */
export function termKey(term: string): string {
  return term.trim().toLowerCase();
}

const KEYS: ReadonlySet<string> = new Set([
  '7/3 repeaters',
  'arcing',
  'auto-belay',
  'backstepping (the twist lock)',
  'band internal / external rotation',
  'band lat pulldowns',
  'band pull-aparts',
  'bear crawl',
  'belay',
  'belay device',
  'belayer',
  'bench press',
  'beta',
  'bird-dog',
  'bouldering',
  'box breathing',
  'box jumps',
  'box sit-to-stand',
  'bulgarian split squats',
  'campus board — double dynos',
  'campus board — laddering',
  'campus board — skips',
  'campus ladder',
  'campus laddering',
  'capacity laps',
  'cat-cow',
  'chalk',
  'compression (the bear hug)',
  'compression plank',
  'core plank',
  'crag',
  'crash pad',
  'crux',
  'crux section links',
  'db chest fly',
  'db overhead press',
  'db pullovers',
  'dead bugs',
  'deadlifts',
  'deep box step-ups',
  'deep squat hold',
  'deload week',
  'density hangs',
  'depth jumps',
  'dips',
  'down dog to cobra',
  'eccentric',
  'eccentric wrist flexor curls',
  'explosive pull-ups',
  'face pull (band)',
  'face pulls with external rotation',
  'finger extensions',
  'flagging',
  'flagging drill',
  'flapper',
  'flash',
  'flow state',
  'flutters',
  'font grade (fontainebleau)',
  'forearm pronation / supination',
  'free solo',
  'french grade',
  'frenchies',
  'frog stretch',
  'front lever progression',
  'front lever tuck holds',
  'full crimp',
  'glute bridges',
  'goblet squat',
  'half crimp',
  'hammer curls',
  'hand jamming',
  'hand matching',
  'hang knee raises',
  'hang leg raises',
  'hanging windshield wipers',
  'harness',
  'hollow body hold',
  'hover hands',
  'i-y-t raises',
  'intro to dynos',
  'inverted rows',
  'isometric',
  'jug',
  'kilter board',
  'knee raises',
  'l-sit',
  'lateral momentum',
  'lead climbing',
  'limit bouldering',
  'linked laps',
  'lunges',
  'lying leg raises',
  'max hangs',
  'min-edge hangs',
  'moonboard',
  'mountain climbers',
  'move-by-move beta decoding',
  'multi-pitch',
  'negatives',
  'offset lock-offs',
  'one-arm negatives',
  'onsight',
  'open hand (the drag)',
  'overhead press',
  'pallof press',
  'passive bar hang (dead hang)',
  'penguins',
  'pigeon pose',
  'plank (forearm)',
  'plank hip dips',
  'projecting',
  'pumped',
  'push-up to plank',
  'push-ups',
  'quickdraw',
  'quiet feet',
  'reading sequences',
  'recruitment ladder',
  'redpoint',
  'redpoint burns',
  'reverse lunges',
  'rice bucket extensors',
  'rkc plank',
  'romanian deadlift (rdl)',
  'rpe (rate of perceived exertion)',
  'run-and-jump (parkour)',
  'run-and-jumps',
  'russian twists',
  'sandbagged',
  'scapular engagement',
  'scapular pull-ups',
  'scapular punches',
  'scapular shrugs (hanging)',
  'scumming',
  'self-analysis',
  'send',
  'side plank',
  'side/front delt raises',
  'smearing',
  'sport climbing',
  'squats',
  'stemming',
  'step-up dyno',
  'step-ups',
  'sticky feet',
  'supermans',
  'system board',
  'tendon density',
  'tension board',
  'the 1-2 (coordination catch)',
  'the bat hang',
  'the bicycle',
  'the bump',
  'the coil',
  'the commitment switch',
  'the coordinate',
  'the deadpoint',
  'the double clutch',
  'the drop knee',
  'the dyno',
  'the figure four',
  'the foot swap',
  'the full send',
  'the gaston',
  'the heel hook',
  'the knee bar',
  'the layback',
  'the mantle',
  'the meat hook (wrist scum)',
  'the paddle (bumping)',
  'the paddle dyno',
  'the pinch',
  'the pocket',
  'the pogo (moon-kick)',
  'the polarization model',
  'the rockover',
  'the rose move',
  'the same side principle',
  'the scissor kick (switch-blade)',
  'the sidepull',
  'the skate',
  'the sloper',
  'the toe hook',
  'the toe-stab',
  'the undercling',
  'the vector',
  'thoracic rotations',
  'time under tension (tut)',
  'toeing-in (edging)',
  'toes-to-bar',
  'top-rope',
  'topo',
  'total max weight',
  'trad climbing',
  'v-scale (v-grade)',
  'v-ups',
  'vertical deadpoint',
  'visualization',
  'volume',
  'wall angels',
  'whip / whipper',
  'wide-grip pull-ups',
  'world\'s greatest stretch',
  'wrist extensor curls',
  'wrist flexor curls',
  'yds (yosemite decimal system)',
  'zone 1 cardio',
]);

/** Whether the glossary defines this exact name. */
export function hasGlossaryTerm(term: string): boolean {
  return KEYS.has(termKey(term));
}

/** Every key, for the tests that hold this file to the glossary. */
export function glossaryKeys(): string[] {
  return [...KEYS];
}
