import type { Drill } from '../types';

/** Drills sourced from Base Camp (12-Week Climbing Foundations). */
export const BASE_CAMP_DRILLS: Drill[] = [
  {
    id: 'sticky_feet',
    name: 'Sticky Feet',
    duration: '45-60 min',
    focus: 'Footwork Precision',
    loads: [],
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'flagging',
    name: 'Flagging',
    duration: '45-60 min',
    focus: 'Body Positioning',
    loads: ['hook'],
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'hover_hands_3s_pause',
    name: 'Hover Hands (3s pause)',
    duration: '45-60 min',
    focus: 'Static Control',
    loads: [],
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'the_trifecta_all_three',
    name: 'The Trifecta (all three)',
    duration: '45-60 min',
    focus: 'Integrated Technique',
    loads: [],
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'endurance_intervals_4x4',
    name: '4x4 Endurance Intervals',
    duration: '60 min',
    focus: 'Endurance Capacity',
    loads: ['shoulder', 'forearm'],
    category: 'endurance',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'volume_build_mini_assessment',
    name: 'Volume Build + Mini-Assessment',
    duration: '60-75 min',
    focus: 'Capacity + Metrics',
    loads: ['fingers', 'pull', 'shoulder'],
    category: 'assessment',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'continuous_circuit_5_10_min',
    name: 'Continuous Circuit 5-10 min',
    duration: '45-60 min',
    focus: 'Pump Management',
    loads: ['sustained'],
    category: 'endurance',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'deload_flow_rpe_5',
    name: 'Deload: Flow RPE 5',
    duration: '30-45 min',
    focus: 'Recovery',
    loads: [],
    category: 'recovery',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'box_breathing_projecting',
    name: 'Box Breathing + Projecting',
    duration: '60 min',
    focus: 'Mental Training',
    loads: [],
    category: 'mental',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'intro_to_dynos',
    name: 'Intro to Dynos',
    duration: '45-60 min',
    focus: 'Dynamic Movement',
    loads: ['dynamic', 'shoulder'],
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'send_week_foundations',
    name: 'Send Week',
    duration: '60-90 min',
    focus: 'Performance',
    loads: ['shoulder'],
    category: 'performance',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'graduation_retest_foundations',
    name: 'Graduation Retest',
    duration: '60 min',
    focus: 'Assessment',
    loads: ['fingers', 'pull', 'sustained', 'shoulder', 'core'],
    category: 'assessment',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },

];
