import type { Drill } from '../types';

/** Drills sourced from Base Camp (12-Week Climbing Foundations). */
export const BASE_CAMP_DRILLS: Drill[] = [
  {
    id: 'sticky_feet',
    name: 'Sticky Feet',
    description:
      'Climb 6-8 V0-V2 boulders at RPE 4-5. Rule: once a foot is placed on a hold, it does NOT move until you step to the next hold. No readjusting, no pivoting, no "just a nudge." Forces you to commit to foot placement before weighting — the root habit of precise climbing. If you catch yourself adjusting, downclimb and restart.',
    duration: '45-60 min',
    focus: 'Footwork Precision',
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'flagging',
    name: 'Flagging',
    description:
      'Climb 6-8 moderate boulders. On every reach with your RIGHT hand, flag your LEFT leg behind you (outside flag or back flag) to counterbalance. Same for left-hand reaches with the right leg. Flagging prevents the barn-door swing that cuts feet. Climb slower than usual to think through each reach.',
    duration: '45-60 min',
    focus: 'Body Positioning',
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'hover_hands_3s_pause',
    name: 'Hover Hands (3s pause)',
    description:
      'Before placing each hand on a hold, hover it above the target for a 3-count. Stay still — no micro-adjustments, no eyeing the next move. Place precisely, commit, move on. Forces static body position under load and trains the nervous system to find the quiet position between moves.',
    duration: '45-60 min',
    focus: 'Static Control',
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['none'],
    sources: ['base_camp'],
  },
  {
    id: 'the_trifecta_all_three',
    name: 'The Trifecta (all three)',
    description:
      'Combine Sticky Feet + Flagging + Hover Hands on every climb. 6-8 boulders, V-easy. This is the hardest drill week because all three constraints compound — a session finishes slower than normal. Quality over quantity: one beautifully climbed boulder beats five messy ones.',
    duration: '45-60 min',
    focus: 'Integrated Technique',
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'endurance_intervals_4x4',
    name: '4x4 Endurance Intervals',
    description:
      'Pick 4 boulders you can flash (2 grades below your max). Climb all 4 back-to-back with no rest between boulders. Rest 3 min. Repeat for 4 rounds = 16 climbs total. Heart rate stays elevated, forearms learn to recover while climbing. If you can’t complete a round, downgrade one boulder and continue.',
    duration: '60 min',
    focus: 'Endurance Capacity',
    category: 'endurance',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'volume_build_mini_assessment',
    name: 'Volume Build + Mini-Assessment',
    description:
      'First half: retest Max Push-Ups, Max Pull-Ups, Dead Hang. Log to Assessment. Second half: climb 20-30 boulders at Flash grade minus 1. Keep Quiet Feet discipline throughout. This week is your first measurable check-in against Week 0 baselines.',
    duration: '60-75 min',
    focus: 'Capacity + Metrics',
    category: 'assessment',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'continuous_circuit_5_10_min',
    name: 'Continuous Circuit 5-10 min',
    description:
      'Build a route by traversing along the easy wall. Climb continuously for 5 minutes without stepping down. Rest 3 min. Repeat 3-4 times, adding 30s to each round. Trains aerobic endurance and pump management. Focus on resting on good holds mid-climb — the ability to rest on the wall is a learnable skill.',
    duration: '45-60 min',
    focus: 'Pump Management',
    category: 'endurance',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'deload_flow_rpe_5',
    name: 'Deload: Flow RPE 5',
    description:
      'Intentional easy week. Climb 30 min at RPE 5 on terrain 2+ grades below max. No drills, no constraints — just fluid, relaxed climbing. Recovery week before the mental-game phase. Sleep matters more than the session. Reduce all Engine Room sets to 2.',
    duration: '30-45 min',
    focus: 'Recovery',
    category: 'recovery',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'box_breathing_projecting',
    name: 'Box Breathing + Projecting',
    description:
      'Pick a project 1-2 grades above your flash level. Before every attempt, do 4 rounds of box breathing: inhale 4s, hold 4s, exhale 4s, hold 4s. Slows the heart rate, focuses attention, and builds the pre-attempt ritual. 3-5 attempts total, 5 min rest between. The breathing is the drill, not the send.',
    duration: '60 min',
    focus: 'Mental Training',
    category: 'mental',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['none'],
    sources: ['base_camp'],
  },
  {
    id: 'intro_to_dynos',
    name: 'Intro to Dynos',
    description:
      'Pick 3-4 juggy V0-V2 boulders. Instead of reaching for each hold, generate momentum and commit to a small dynamic move. Start with mini-pops (both feet stay on) and progress to full deadpoints. This is the FIRST exposure to dynamic movement — form over distance. If you feel any shoulder tweak, stop and switch to static.',
    duration: '45-60 min',
    focus: 'Dynamic Movement',
    category: 'technique',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['wall'],
    sources: ['base_camp'],
  },
  {
    id: 'send_week_foundations',
    name: 'Send Week',
    description:
      'Pick the hardest project you’ve been eyeing. Apply everything: Quiet Feet, Flagging, Hover Hands when possible, Box Breathing before each attempt. 3-5 quality burns, 5-10 min rest between. This is your first performance peak. If you send, try the next grade up. If you don’t, the beta is banked for next cycle.',
    duration: '60-90 min',
    focus: 'Performance',
    category: 'performance',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['none'],
    sources: ['base_camp'],
  },
  {
    id: 'graduation_retest_foundations',
    name: 'Graduation Retest',
    description:
      'Repeat every Week 0 baseline: Max Push-Ups, Max Pull-Ups, Dead Hang, Core Plank, Flash Grade, Capacity Test (4x4). Log everything — this is your graduation scorecard. Compare to Week 0 numbers; the data rules the story.',
    duration: '60 min',
    focus: 'Assessment',
    category: 'assessment',
    discipline: 'both',
    level: 'V0-V2',
    equipment: ['none'],
    sources: ['base_camp'],
  },

];
