import type { Drill } from '../types';

/** Drills sourced from Gravity Defied (12-Week Dynamic Climbing). */
export const GRAVITY_DEFIED_DRILLS: Drill[] = [
  // ── Technical Flight (weekly dyno drill) ────────────────────────────────
  {
    id: 'vertical_deadpoint',
    name: 'Vertical Deadpoint (The Hips-In Hover)',
    description:
      'Pick 3-5 problems with a clear straight-up dyno move. Sink hips LOW, arms stay straight. Explode using legs — do NOT pull with arms first. At the top of the arc (the deadpoint), do NOT grab — just slap or hover over the target hold. RPE 6-7. If your elbows bend before your hips leave the wall, restart. The arms are ropes, not motors.',
    duration: '45-60 min',
    focus: 'Leg-Driven Launch',
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'lateral_momentum',
    name: 'Lateral Momentum (The Side-Step Swing)',
    description:
      'Traverse dynamically on juggy terrain. The trailing leg is your engine — push sideways off it to swing hips in the direction of the next hold. Cue: "push with the foot." Hips lead, hands follow. 4-6 traverse problems, 2-3 reps each. Do not muscle the reach; redirect momentum.',
    duration: '45-60 min',
    focus: 'Horizontal Force',
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'double_clutch',
    name: 'Double Clutch (The Clap)',
    description:
      'On dyno-friendly boulders, launch and CLAP hands mid-air before latching the target hold. The clap forces full commitment — you cannot half-attempt a move while clapping. 3-5 problems, RPE 6-7. Drops the safety net that keeps dynos feeling underpowered.',
    duration: '45-60 min',
    focus: 'Commitment',
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_pogo',
    name: 'The Pogo (One-Leg Swing / Moon-Kick)',
    description:
      'Set up with one foot on a hold, the other free. Swing the free leg back, then KICK forward and up to generate momentum. The kick happens BEFORE the pull. This is the "free-leg engine" most boulderers ignore. 4-6 attempts per side on moderate terrain.',
    duration: '45-60 min',
    focus: 'Free-Leg Momentum',
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'step_up_dyno',
    name: 'Step-Up Dyno (The High-Box Drive)',
    description:
      'Put weight over a high foothold. Press through the HEEL to drive up — this recruits the glute instead of the quad. 3-4 problems with high-step dyno sequences. The press should feel like standing up from a deep single-leg squat with a launch at the top.',
    duration: '45-55 min',
    focus: 'Glute-Driven Power',
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_paddle_bumping',
    name: 'The Paddle / Bumping (Hot Potato)',
    description:
      'Dyno to an intermediate hold, then BUMP to the finish hold in under half a second. Do not hang on the intermediate — it is a stepping stone. Trains contact strength plus the ability to re-launch from a partially loaded position. 3-4 problems with bumpable sequences.',
    duration: '45-55 min',
    focus: 'Chain Dynamics',
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'run_and_jumps',
    name: 'Run-and-Jumps (The Volume Run)',
    description:
      'Run alongside the wall, step on volumes, catch a high hold. Commits you to a fully dynamic attack with both feet airborne mid-attempt. Landings matter — absorb with knees and hips, hands off the ground. 3-5 attempts, only on juggy finish holds.',
    duration: '45-60 min',
    focus: 'Full-Body Momentum',
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'deload_target_practice',
    name: 'DELOAD: Target Practice',
    description:
      'Intentional easy week to let the CNS recover from 7 weeks of high-force work. Reduce all dyno attempts 30%. On each attempt, touch the target hold with your INDEX FINGER specifically — the accuracy constraint forces light touches. No limit attempts. Sleep is the training this week.',
    duration: '30-45 min',
    focus: 'Recovery + Precision',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_coordinate',
    name: 'The Coordinate (Multi-Move Cascade)',
    description:
      'Chain TWO or more dynamic moves you have learned in Phase 1-2 on a single boulder. Sequence momentum — exit of move 1 becomes the setup for move 2. This is where drills become real climbing. 2-3 problems, 3-5 attempts each.',
    duration: '60 min',
    focus: 'Sequence Integration',
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_full_send',
    name: 'The Full Send (Simultaneous Catch / Rooted Launch)',
    description:
      'On overhangs, toes grip like talons and pull the wall TOWARD you as the hands leave. Maintain toe-tension through the air. For the catch, hand and foot contact the new holds at the exact same moment — arrests swing. 3-4 attempts on overhanging projects.',
    duration: '60 min',
    focus: 'Overhang Commitment',
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'integration_project_week',
    name: 'Integration (Project Week)',
    description:
      'Pick a limit boulder requiring at least one dynamic move you have drilled this program. Apply the Commitment Switch: first 3 attempts explode 100% but do NOT latch — tap and control landing. Attempts 4+: same power, open hand, latch. 4-6 quality burns, 5 min rest between.',
    duration: '60-90 min',
    focus: 'Performance',
    category: 'performance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'graduation_flight_test',
    name: 'Graduation Flight Test',
    description:
      'Retest Box Jump Height, Explosive Pull-Ups, Dead Hang, and Max Dynamic Grade. Then attempt a graduation boulder: a V4-V5 requiring 2+ dynamic skills, or 1-2 grades above your starting flash. Log everything. This is your scorecard vs Week 0.',
    duration: '60-90 min',
    focus: 'Assessment',
    category: 'assessment',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },

  // ── Performance & Limit (weekly hard-effort session) ────────────────────
  {
    id: 'limit_dynos_four_burns',
    name: 'Limit Dynos — 4 Burns per Problem',
    description:
      'Warm up 25-30 min — dynamic movement needs full tissue temperature and primed shoulders. Pick 3-4 boulders at your limit that force a committing dynamic move (deadpoint, dyno, or big throw). 4 quality burns each, 4-5 min rest between burns, 8+ min between problems. Log the hardest dyno you attempt and whether you stick the landing. End a problem after two ugly burns in a row — sloppy dynamic climbing trains bad motor patterns and risks your ankles on the fall.',
    duration: '60-75 min',
    focus: 'Dynamic Limit Intro',
    category: 'power',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'style_diverse_dynamic_day',
    name: 'Style-Diverse Dynamic Day',
    description:
      'Pick 4-5 limit problems that each demand a DIFFERENT dynamic style — one straight-up deadpoint, one lateral swing, one paddle or bump, one all-out commitment throw. 3-4 burns each. The point is breadth: your launch and catch have to work in every direction, not just your favourite one. Rate landing quality honestly — a caught-but-barn-door catch is not a clean send.',
    duration: '60-75 min',
    focus: 'Movement Breadth',
    category: 'power',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'crux_isolation_hard_move',
    name: 'Crux Isolation — The Hard Move',
    description:
      'Pick ONE dynamic project just beyond your level. For the first 30 min, isolate the crux move off the start holds or a pad — drill the launch and catch in isolation: hip drive, timing, body tension on the catch. Then link it into the full problem. This is move-mastery under maximal force, not volume. Rest fully (5+ min) between real attempts; quality beats quantity here.',
    duration: '60-75 min',
    focus: 'Crux Power',
    category: 'power',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'deload_flow_dynos',
    name: 'DELOAD: Flow Dynos',
    description:
      'Deload week — drop intensity hard. 5-6 boulders well within your limit that still move dynamically, at RPE 5-6. Focus purely on smooth, precise launches and soft, controlled landings. No projecting, no max throws. The catch tissues (shoulders, fingers) and your nervous system need this week to absorb the first block. Climb, do not grind.',
    duration: '40-50 min',
    focus: 'Recovery + Precision',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'intensify_five_burns',
    name: 'Intensify — 5 Burns at Limit',
    description:
      'The hardest dynamic block. Pick 3 limit problems with committing dynamic cruxes, 5 quality burns each, 5 min rest between burns. Push the grade you attempt above Block 1. Your catches should feel noticeably more secure than four weeks ago. Log the hardest dyno you send — you should be banking sends now, not just attempts.',
    duration: '75-90 min',
    focus: 'Peak Dynamic Volume',
    category: 'power',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'dynamic_link_ups',
    name: 'Dynamic Link-Ups',
    description:
      'Pick 2-3 moderate problems (1-2 grades below limit) that chain back-to-back dynamic moves. Climb each TWICE back-to-back with no rest, 3-4 sets, 4 min rest between sets. This builds the power-endurance to throw a second and third dyno when already pumped — the thing that ends most dynamic boulders. Form first; if the catches turn to flails, the set is done.',
    duration: '75 min',
    focus: 'Power-Endurance',
    category: 'power-endurance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_hard_flash_day',
    name: 'The Hard-Flash Day',
    description:
      'Pick 5-6 unfamiliar dynamic problems one grade below your max and try to FLASH each — read the dynamic beta from the ground and commit fully on the first go. Dynamic climbing punishes hesitation, so this trains reading momentum and committing without rehearsal. 2 attempts max per problem, then move on. Log how many you flash clean.',
    duration: '75 min',
    focus: 'First-Go Commitment',
    category: 'strategy',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'deload_soft_catches',
    name: 'DELOAD: Soft Catches',
    description:
      'Second deload — line it up with your Technique deload for a true rest week. 5-6 easy problems at RPE 5, dynamic but well within limit. Treat every catch as a precision rep: exact hand placement, quiet landing, no swing. This is the last reset before the performance phase. Sleep and eat like it is part of the training, because it is.',
    duration: '45 min',
    focus: 'Recovery',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'peak_projecting_six_burns',
    name: 'Peak Projecting — 6 Burns',
    description:
      'Performance phase. Pick 2-3 of your hardest dynamic projects, 6 burns each, full 5+ min rest. You are strong and recovered now — this is where the block’s hardest dynamic sends happen. Treat every burn like the send: precise warm-up, full commitment, soft landing. Log the hardest dyno you attempt; it should be a personal best.',
    duration: '75-90 min',
    focus: 'Send-Level Dynos',
    category: 'performance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'send_window',
    name: 'Send Window',
    description:
      'Prime conditions, prime effort. Pick your single best dynamic project and give it real send burns — 4-6 attempts with long rest and no junk volume around them. Warm up thoroughly but conserve; the goal is the send, not a workout. Send it early? Bank it and move to the next project. Log the send and the landing quality.',
    duration: '75 min',
    focus: 'Send Performance',
    category: 'performance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'consolidate_and_convert',
    name: 'Consolidate & Convert',
    description:
      'Convert the gains. Revisit 2-3 dynamic problems that were at your limit four weeks ago — they should go cleanly now. Then push one grade harder on a fresh dynamic project. This proves the block worked and resets your baseline. Keep volume moderate; you are sharpening, not breaking down before the test.',
    duration: '75 min',
    focus: 'Performance',
    category: 'performance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'graduation_send_test',
    name: 'Graduation: The Send Test',
    description:
      'Graduation. Warm up fully, then attempt the hardest dynamic boulder you can — your performance flight test. Whether you send or just bank the beta, log your hardest dyno attempted and sent for the program. Compare to Week 1: a one-to-two-grade jump in dynamic sending is a strong result. Celebrate the send, then choose your next program.',
    duration: '75-90 min',
    focus: 'Assessment + Final Send',
    category: 'assessment',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
];
