import type { Drill } from '../types';

/** Drills sourced from Gravity Defied (12-Week Dynamic Climbing). */
export const GRAVITY_DEFIED_DRILLS: Drill[] = [
  // ── Technical Flight (weekly dyno drill) ────────────────────────────────
  {
    id: 'vertical_deadpoint',
    name: 'Vertical Deadpoint (The Hips-In Hover)',
    duration: '45-60 min',
    focus: 'Leg-Driven Launch',
    loads: ['dynamic', 'hip'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'lateral_momentum',
    name: 'Lateral Momentum (The Side-Step Swing)',
    duration: '45-60 min',
    focus: 'Horizontal Force',
    loads: ['dynamic', 'sustained', 'hip'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'double_clutch',
    name: 'Double Clutch (The Clap)',
    duration: '45-60 min',
    focus: 'Commitment',
    loads: ['dynamic'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_pogo',
    name: 'The Pogo (One-Leg Swing / Moon-Kick)',
    duration: '45-60 min',
    focus: 'Free-Leg Momentum',
    loads: [],
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'step_up_dyno',
    name: 'Step-Up Dyno (The High-Box Drive)',
    duration: '45-55 min',
    focus: 'Glute-Driven Power',
    loads: ['dynamic', 'hook', 'legs'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_paddle_bumping',
    name: 'The Paddle / Bumping (Hot Potato)',
    duration: '45-55 min',
    focus: 'Chain Dynamics',
    loads: ['dynamic'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'run_and_jumps',
    name: 'Run-and-Jumps (The Volume Run)',
    duration: '45-60 min',
    focus: 'Full-Body Momentum',
    loads: ['dynamic', 'hip', 'legs'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'deload_target_practice',
    name: 'DELOAD: Target Practice',
    duration: '30-45 min',
    focus: 'Recovery + Precision',
    loads: ['dynamic'],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_coordinate',
    name: 'The Coordinate (Multi-Move Cascade)',
    duration: '60 min',
    focus: 'Sequence Integration',
    loads: ['dynamic'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_full_send',
    name: 'The Full Send (Simultaneous Catch / Rooted Launch)',
    duration: '60 min',
    focus: 'Overhang Commitment',
    loads: [],
    category: 'technique',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'integration_project_week',
    name: 'Integration (Project Week)',
    duration: '60-90 min',
    focus: 'Performance',
    loads: ['dynamic', 'open-hand', 'legs'],
    category: 'performance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'graduation_flight_test',
    name: 'Graduation Flight Test',
    duration: '60-90 min',
    focus: 'Assessment',
    loads: ['fingers', 'pull', 'dynamic', 'legs'],
    category: 'assessment',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },

  // ── Performance & Limit (weekly hard-effort session) ────────────────────
  {
    id: 'limit_dynos_four_burns',
    name: 'Limit Dynos — 4 Burns per Problem',
    duration: '60-75 min',
    focus: 'Dynamic Limit Intro',
    loads: ['dynamic', 'shoulder', 'legs'],
    category: 'power',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'style_diverse_dynamic_day',
    name: 'Style-Diverse Dynamic Day',
    duration: '60-75 min',
    focus: 'Movement Breadth',
    loads: ['dynamic', 'legs'],
    category: 'power',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'crux_isolation_hard_move',
    name: 'Crux Isolation — The Hard Move',
    duration: '60-75 min',
    focus: 'Crux Power',
    loads: ['dynamic', 'hip'],
    category: 'power',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'deload_flow_dynos',
    name: 'DELOAD: Flow Dynos',
    duration: '40-50 min',
    focus: 'Recovery + Precision',
    loads: ['dynamic', 'shoulder', 'legs'],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'intensify_five_burns',
    name: 'Intensify — 5 Burns at Limit',
    duration: '75-90 min',
    focus: 'Peak Dynamic Volume',
    loads: ['dynamic'],
    category: 'power',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'dynamic_link_ups',
    name: 'Dynamic Link-Ups',
    duration: '75 min',
    focus: 'Power-Endurance',
    loads: ['dynamic'],
    category: 'power-endurance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'the_hard_flash_day',
    name: 'The Hard-Flash Day',
    duration: '75 min',
    focus: 'First-Go Commitment',
    loads: ['dynamic'],
    category: 'strategy',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'deload_soft_catches',
    name: 'DELOAD: Soft Catches',
    duration: '45 min',
    focus: 'Recovery',
    loads: ['dynamic', 'legs'],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'peak_projecting_six_burns',
    name: 'Peak Projecting — 6 Burns',
    duration: '75-90 min',
    focus: 'Send-Level Dynos',
    loads: ['dynamic', 'legs'],
    category: 'performance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'send_window',
    name: 'Send Window',
    duration: '75 min',
    focus: 'Send Performance',
    loads: ['dynamic', 'legs'],
    category: 'performance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'consolidate_and_convert',
    name: 'Consolidate & Convert',
    duration: '75 min',
    focus: 'Performance',
    loads: ['dynamic'],
    category: 'performance',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
  {
    id: 'graduation_send_test',
    name: 'Graduation: The Send Test',
    duration: '75-90 min',
    focus: 'Assessment + Final Send',
    loads: ['dynamic'],
    category: 'assessment',
    discipline: 'boulder',
    level: 'V2-V5',
    equipment: ['wall'],
    sources: ['gravity_defied'],
  },
];
