import type { Drill } from '../types';

/** Drills sourced from Iron Grip (12-Week Finger Strength). */
export const IRON_GRIP_DRILLS: Drill[] = [
  {
    id: 'limit_boulders_on_the_crimps',
    name: 'Limit Boulders on the Crimps',
    description:
      'Pick 3-5 crimpy boulders at your limit minus 1 grade. Climb each 2-3 times, resting 3-5 min between burns. Focus on precise crimp placement and purposeful body position. If you feel any finger tweak, STOP — Repeater phase should not push into pain.',
    duration: '45-60 min',
    focus: 'Crimp Strength Application',
    category: 'finger-strength',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'volume_on_moderate_crimps',
    name: 'Volume on Moderate Crimps',
    description:
      '20-25 moderate boulders (2 grades below max) with crimp holds. Move through them steadily, rest 1-2 min between. Builds tendon tolerance and crimp-position mileage. The Anvil phase is about time-on-the-edge — this accumulates it.',
    duration: '45-60 min',
    focus: 'Tendon Mileage',
    category: 'finger-strength',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'projecting_with_crimp_focus',
    name: 'Projecting With Crimp Focus',
    description:
      'Pick 2-3 limit projects featuring crimp moves. Bias your beta toward crimp holds even when pinch or jug alternatives exist — this is the applied version of the hangboard work. 4-6 burns per project, 5 min rest.',
    duration: '60-90 min',
    focus: 'Applied Crimp Strength',
    category: 'finger-strength',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'deload_flow_session',
    name: 'DELOAD: Flow Session',
    description:
      'End of Phase 1. Intentional easy week — no crimp focus, no limit attempts. Climb 30-45 min at RPE 5 on juggy terrain. Sleep and protein matter more than the session. The Hammer phase is about to demand everything; arrive fresh.',
    duration: '30-45 min',
    focus: 'Recovery',
    category: 'recovery',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'power_endurance_circuit',
    name: 'Power Endurance Circuit',
    description:
      'Pick 4-6 boulders at 2-3 grades below your max. Climb them back-to-back with no rest, then rest 4 minutes. Repeat 3-4 sets. Builds the ability to pull hard repeatedly — where your new max hangs will actually pay off in real climbing.',
    duration: '45-60 min',
    focus: 'Power Endurance',
    category: 'power-endurance',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'limit_bouldering_sessions',
    name: 'Limit Bouldering Sessions',
    description:
      'Peak intensity climbing. Pick 2-3 projects at or above your max grade. 5-8 burns per project with 5+ min rest. This is where Phase 2’s max hang gains show up. Take a full rest day after — Max Hang sessions and limit climbing together is heavy CNS load.',
    duration: '60-90 min',
    focus: 'Limit Strength',
    category: 'power',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'the_crimp_project',
    name: 'The Crimp Project',
    description:
      'Find a project that scared you 6 weeks ago because of its crimps. Attempt it now — burn after burn, 5-10 min rest. You may not send. You will be shocked at how different it feels. Collect beta, note the crux, set a plan for Phase 3.',
    duration: '60-90 min',
    focus: 'Projecting',
    category: 'strategy',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'deload_max_hang_day_off_flow',
    name: 'DELOAD: Max-Hang-Day-Off Flow',
    description:
      'End of Phase 2. Very easy climbing only. No hangboard this week. Sleep + food > sessions. Campus board is about to enter the picture — your fingers need to be fully recovered.',
    duration: '30-45 min',
    focus: 'Recovery',
    category: 'recovery',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'contact_strength_projecting',
    name: 'Contact Strength Projecting',
    description:
      'Pick 2-3 max-grade projects with dynamic moves — dyno, paddle, deadpoint. Focus on projecting the crux — the single hardest move — with long rests (5+ min). This is where campus-board power meets real rock. Quality over quantity.',
    duration: '60-90 min',
    focus: 'Contact Strength',
    category: 'power',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'crimp_pull_power_application',
    name: 'Crimp Pull-Power Application',
    description:
      'Campus board recruits fast-twitch; the wall is where you cash it in. Pick 3-4 boulders with BOTH small crimps AND dynamic moves. Burn them hard — 3-5 attempts each, full rest. Film yourself if possible; campus-phase form breaks quickly.',
    duration: '60-90 min',
    focus: 'Power + Crimp Integration',
    category: 'finger-strength',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'send_week_crimp',
    name: 'Send Week',
    description:
      'Peak performance of the program. Pick your hardest crimp project and commit the week to sending it. 2 sessions of 4-6 quality burns each with long rest. Box Breathe before each attempt. This is what 12 weeks of finger work paid for.',
    duration: '60-90 min',
    focus: 'Performance',
    category: 'performance',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'graduation_retest_fingers',
    name: 'Graduation Retest',
    description:
      'Retest every Week 0 baseline: Max Hang at 20mm, Weighted Pull-Ups 3RM, 90° Lock-Off, Core Lever progression, Max Pull-Ups, Dead Hang. Log everything. Then rest 3 full days before any climbing — transition to deload maintenance.',
    duration: '60 min',
    focus: 'Assessment',
    category: 'assessment',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['hangboard', 'wall'],
    sources: ['iron_grip'],
  },
];
