import type { Drill } from '../types';

/** Drills sourced from Iron Grip (12-Week Finger Strength). */
export const IRON_GRIP_DRILLS: Drill[] = [
  {
    id: 'limit_boulders_on_the_crimps',
    name: 'Limit Boulders on the Crimps',
    duration: '45-60 min',
    focus: 'Crimp Strength Application',
    loads: ['fingers'],
    category: 'finger-strength',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'volume_on_moderate_crimps',
    name: 'Volume on Moderate Crimps',
    duration: '45-60 min',
    focus: 'Tendon Mileage',
    loads: ['fingers'],
    category: 'finger-strength',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'projecting_with_crimp_focus',
    name: 'Projecting With Crimp Focus',
    duration: '60-90 min',
    focus: 'Applied Crimp Strength',
    loads: ['fingers', 'open-hand'],
    category: 'finger-strength',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'deload_flow_session',
    name: 'DELOAD: Flow Session',
    duration: '30-45 min',
    focus: 'Recovery',
    loads: ['fingers'],
    category: 'recovery',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'power_endurance_circuit',
    name: 'Power Endurance Circuit',
    duration: '45-60 min',
    focus: 'Power Endurance',
    loads: ['fingers'],
    category: 'power-endurance',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'limit_bouldering_sessions',
    name: 'Limit Bouldering Sessions',
    duration: '60-90 min',
    focus: 'Limit Strength',
    loads: ['fingers'],
    category: 'power',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'the_crimp_project',
    name: 'The Crimp Project',
    duration: '60-90 min',
    focus: 'Projecting',
    loads: ['fingers'],
    category: 'strategy',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'deload_max_hang_day_off_flow',
    name: 'DELOAD: Max-Hang-Day-Off Flow',
    duration: '30-45 min',
    focus: 'Recovery',
    loads: ['campus', 'fingers'],
    category: 'recovery',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'contact_strength_projecting',
    name: 'Contact Strength Projecting',
    duration: '60-90 min',
    focus: 'Contact Strength',
    loads: ['campus', 'dynamic'],
    category: 'power',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'crimp_pull_power_application',
    name: 'Crimp Pull-Power Application',
    duration: '60-90 min',
    focus: 'Power + Crimp Integration',
    loads: ['campus', 'fingers', 'dynamic'],
    category: 'finger-strength',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'send_week_crimp',
    name: 'Send Week',
    duration: '60-90 min',
    focus: 'Performance',
    loads: ['fingers'],
    category: 'performance',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['wall'],
    sources: ['iron_grip'],
  },
  {
    id: 'graduation_retest_fingers',
    name: 'Graduation Retest',
    duration: '60 min',
    focus: 'Assessment',
    loads: ['fingers', 'lever', 'pull', 'core'],
    category: 'assessment',
    discipline: 'both',
    level: 'V5-V8',
    equipment: ['hangboard', 'wall'],
    sources: ['iron_grip'],
  },
];
