import type { Drill } from '../types';

/** Drills sourced from Lockdown (12-Week Static Power). */
export const LOCKDOWN_DRILLS: Drill[] = [
  {
    id: 'quiet_feet_hover_hands',
    name: 'Quiet Feet + 3-Second Hover Hands',
    duration: '30-40 min',
    focus: 'Body Positioning & Static Control',
    loads: [],
    category: 'technique',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'drop_knee_isolation',
    name: 'Drop-Knee Isolation',
    duration: '30-40 min',
    focus: 'Hip Rotation',
    loads: ['hook', 'hip'],
    category: 'technique',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'heel_hook_commitment',
    name: 'Heel Hook Commitment',
    duration: '30-40 min',
    focus: 'Lower Body Engagement',
    loads: ['sustained', 'hook', 'hip'],
    category: 'technique',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'static_trifecta',
    name: 'The Trifecta (Quiet Feet + Hover + Drop-Knee)',
    duration: '45-55 min',
    focus: 'Integrated Static Technique',
    loads: ['hook'],
    category: 'technique',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'lock_off_holds_on_wall',
    name: 'Lock-Off Holds on the Wall',
    duration: '30-40 min',
    focus: 'In-Position Strength',
    loads: ['pull'],
    category: 'power',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'twist_lock_practice',
    name: 'Twist-Lock Practice',
    duration: '30-40 min',
    focus: 'Rotational Technique',
    loads: ['hip'],
    category: 'technique',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'static_projecting',
    name: 'Static Projecting',
    duration: '45-60 min',
    focus: 'Static Problem-Solving',
    loads: [],
    category: 'strategy',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'deload_the_flow_session',
    name: 'DELOAD: The Flow Session',
    duration: '30-40 min',
    focus: 'Recovery',
    loads: [],
    category: 'recovery',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'no_match_climbing',
    name: 'No-Match Climbing',
    duration: '30-40 min',
    focus: 'Commitment & Sequencing',
    loads: [],
    category: 'technique',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'offset_pull_practice',
    name: 'Offset Pull Practice',
    duration: '30-40 min',
    focus: 'One-Arm Strength Application',
    loads: ['one-arm'],
    category: 'power',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'project_week_static',
    name: 'Project Week',
    duration: '60-90 min',
    focus: 'Performance',
    loads: ['hook'],
    category: 'performance',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['wall'],
    sources: ['lockdown'],
  },
  {
    id: 'graduation_retest_static',
    name: 'Graduation Retest',
    duration: '60 min',
    focus: 'Assessment',
    loads: ['fingers', 'pull', 'forearm', 'core'],
    category: 'assessment',
    discipline: 'both',
    level: 'V3-V5',
    equipment: ['hangboard', 'wall'],
    sources: ['lockdown'],
  },
];
