import type { Drill } from '../types';

/** Drills sourced from The Long Game (12-Week Route & Endurance). */
export const LONG_GAME_DRILLS: Drill[] = [
  {
    id: 'tlg_arc_2x10',
    protocolId: 'arcing',
    name: 'ARC Pacing — 2x10 min',
    description:
      'Aerobic Restoration and Capillarization. Climb continuously for 10 minutes at RPE 3-4 — easy breathing, sustained MILD pump. No sends, no peak effort. Traverse or lap easy routes 3-4 grades below your on-sight. Rest 5 min. Climb 10 more minutes. ARC does not feel like training — that is the point. The adaptation is vascular. If you pump out, you went too hard.',
    duration: '30-45 min',
    focus: 'Aerobic Base',
    category: 'endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_arc_2x15',
    protocolId: 'arcing',
    name: 'ARC Pacing — 2x15 min',
    description:
      'Same ARC protocol, extend continuous duration to 15 minutes per round. Skill focus this week: straight arms throughout, breathe out on every move. Practice shaking out every 5-8 moves EVEN WHEN FRESH — shaking is a skill you groove now, not a reaction.',
    duration: '45 min',
    focus: 'Aerobic Base + Shakeout',
    category: 'endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_arc_2x20',
    protocolId: 'arcing',
    name: 'ARC Pacing — 2x20 min',
    description:
      'Peak Phase 1 ARC duration. 20 minutes of continuous climbing, rest 5 min, 20 more. Terrain stays 3-4 grades below on-sight. Skill focus: clip practice from 3 different stances per round. Notice which stances feel stable and which force you to pump out — that is beta for your future projects.',
    duration: '60 min',
    focus: 'Aerobic Base + Clipping',
    category: 'endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_deload_arc_movement',
    protocolId: 'arcing',
    name: 'DELOAD: 2x12 min ARC + Movement Quality',
    description:
      'End of Base phase. Reduce ARC to 2x12 min at VERY easy intensity. Focus entirely on perfect movement — quiet feet, read two moves ahead, exhale on every reach. Recovery matters more than stimulus this week. Skip if you feel fresh and need to train; add extra sleep if you do not.',
    duration: '30 min',
    focus: 'Recovery + Movement',
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_linked_laps_doubles',
    name: 'Linked Laps — Doubles',
    description:
      'Phase 2 begins. Pick 2 routes at 80-90% of your redpoint grade. Climb the first, lower, pull immediately onto the second, climb it. Rest 4 minutes. Repeat 3-4 sets. Now you WILL pump — the training is keeping functional while pumped. Phase 1 taught you not to pump; Phase 2 teaches you to climb through it.',
    duration: '60-75 min',
    focus: 'Power Endurance',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_4x4_route_intervals',
    name: '4x4 Route Intervals',
    description:
      '4 moderate routes (2 grades below redpoint) back-to-back with ZERO rest between them. That is one set. Rest 4 min. Repeat 3-4 sets. Brutal forearm-buffering stimulus. If you drop off a route mid-set, the set is over — lower, rest, restart the full set.',
    duration: '60-75 min',
    focus: 'Pump Tolerance',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_the_pump_clock',
    name: 'The Pump Clock',
    description:
      'Climb until you feel pump onset — note the time. Shake out for 10 seconds (timed). Continue climbing. Your goal this session is to EXTEND the time-to-pump window by 20-30%. Try 3 rounds. Teaches active recovery while climbing and builds shakeout efficiency.',
    duration: '60 min',
    focus: 'Pump Management',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_deload_arc_2x10',
    protocolId: 'arcing',
    name: 'DELOAD: 2x10 min ARC',
    description:
      'End of Engine phase. Reduce all intervals to 2 sets maximum. Or just ARC 2x10 easy minutes. Sleep and nutrition are the training this week. Phase 3 needs you fresh — send attempts do not happen in fatigued forearms.',
    duration: '30 min',
    focus: 'Recovery',
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_linked_laps_shakeout',
    name: 'Linked Laps 2 sets + Shakeout Drill',
    description:
      'Phase 3 begins. Short maintenance version of Phase 2 intervals — 2 sets only of linked doubles. Then 10 minutes of intentional shakeout practice on a fresh route: climb, shake, climb, shake. Time each shakeout to 10-15s per arm. Precise shakeouts can save an attempt.',
    duration: '45-60 min',
    focus: 'Send-Week Prep',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_maintenance_linked_laps',
    name: 'Maintenance Linked Laps',
    description:
      'Same 2-set linked laps. Film at least one attempt — watch back between sets for pacing, clipping, and hang points. Your phase 2 engine is now your toolkit; you are refining how you use it, not building more.',
    duration: '45-60 min',
    focus: 'Maintenance',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_arc_taper',
    protocolId: 'arcing',
    name: 'ARC 1x15 min (Taper Week)',
    description:
      'Massive taper. Single ARC round, 15 minutes, very easy. No intensity work. You are conserving everything for send day. Rest more than you think you need.',
    duration: '20 min',
    focus: 'Send Taper',
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_no_endurance_send_week',
    name: 'No Endurance — Send Week',
    description:
      'No dedicated endurance session this week. Your endurance sessions this week are your send attempts themselves. Rest, sleep, protein, patience. The training is done.',
    duration: '0 min',
    focus: 'Send Week',
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_onsight_route_reading',
    name: 'On-Sight Practice + Route Reading',
    description:
      '3-5 routes at your on-sight level. Before each route, spend 60 seconds reading it from the ground: note rest positions, cruxes, clipping stances. Attempt the route cold. After each, note where your read was wrong. Route reading is a skill and it is trained here.',
    duration: '60-90 min',
    focus: 'On-Sight Skill',
    category: 'strategy',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_clipping_drills',
    name: 'Clipping Drills',
    description:
      'Pick 3 moderate routes (1-2 grades below on-sight). Climb each twice. First attempt: clip from 3 different stances per clip (left side, right side, direct). Second attempt: practice one-hand, one-motion clipping — no fumbling. If you fumble, re-establish balance and try again. Builds clipping efficiency you will desperately need on redpoints.',
    duration: '60 min',
    focus: 'Clipping Efficiency',
    category: 'technique',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_fall_ladder',
    name: 'Lead Fall Practice — The Fall Ladder',
    description:
      'Use the 4-step fall ladder: (1) Clip fall — climb 1 ft above the bolt and let go; (2) Half-clip — 3-4 ft above; (3) Full-bolt — climb to next bolt without clipping, fall; (4) Commitment fall — attempt a hard move above the bolt, fall naturally. Only progress when the current level feels comfortable. Rebuilds trust in the system.',
    duration: '60 min',
    focus: 'Fall Training',
    category: 'mental',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_deload_easy_onsights',
    name: 'DELOAD: 2-3 Easy On-Sights',
    description:
      'End of Base. 2-3 attempts only on moderate routes. No projecting, no max efforts. Review notes from the past 4 weeks — find patterns in what went wrong on on-sights. Sleep matters more than the session.',
    duration: '45-60 min',
    focus: 'Recovery + Review',
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_project_selection_burns',
    name: 'Project Selection — Working Burns',
    description:
      'Phase 2 performance begins. Pick 1-2 target routes at your redpoint limit. Attempt 1: climb the full route, note every issue. Attempts 2-3: isolate the crux — take the rope, work the moves. Rest 5-8 min between burns. 3-4 burns total per session.',
    duration: '60-90 min',
    focus: 'Project Decoding',
    category: 'strategy',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_crux_to_chains',
    name: 'Crux to Chains / Bottom to Crux',
    description:
      'Same project(s). Now LINK sections. Try bottom-to-crux on burn 1. Crux-to-chains on burn 2. Full redpoint attempt on burn 3 if you have it. 3-5 min rest between burns. Notes after every burn: where did you fall and why?',
    duration: '60-90 min',
    focus: 'Section Linking',
    category: 'strategy',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_full_redpoint_attempts',
    name: 'Full Redpoint Attempts',
    description:
      'Burn-for-burn on your project. 3-4 full redpoint attempts with 8-10 min rest between. Before EVERY burn: visualize every clip, rest, and crux move for 60 seconds. Take brutal notes after each fall. Strength? Technique? Mental? Be specific.',
    duration: '60-90 min',
    focus: 'Full Redpoint',
    category: 'performance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_deload_volume_day',
    name: 'DELOAD: Volume Day',
    description:
      'End of Engine. No projecting. 5-6 moderate routes at a grade below your redpoint. Focus on cruising them with perfect movement — quiet feet, straight arms, slow breathing. Keeps the motor patterns grooved while letting the pump system recover.',
    duration: '60-90 min',
    focus: 'Recovery + Movement',
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_visualization_burns',
    name: 'Visualization + Full Project Burns',
    description:
      'Send phase. Warm up 25-30 min. Before every burn: full visualization of the complete route, 60s minimum, eyes closed. 2-4 full project burns with 8-10 min rest. Decoupling: rate each attempt quality 0-10 INDEPENDENT of send/fail. A perfect attempt that falls is better than a sloppy send.',
    duration: '75-90 min',
    focus: 'Send-Quality Burns',
    category: 'performance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_film_review_projecting',
    name: 'Film + Review Projecting',
    description:
      'Film 2 project attempts from the ground. Watch back between burns. Look for: early arm bending, hip drift away from wall, foot hesitations, rushed clips. Reattempt with the feedback in mind. Video exposes what you cannot feel.',
    duration: '75-90 min',
    focus: 'Technical Refinement',
    category: 'strategy',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_peak_conditions_send',
    name: 'Peak Conditions Send Attempts',
    description:
      'Time the session for peak conditions — coolest, driest part of the day, least-crowded section of the gym. 3 high-quality burns, 10-12 min rest between. Sleep 8+ hrs night before. Warm up 30 min, not 20. This is where 11 weeks of work arrive.',
    duration: '90 min',
    focus: 'Peak Send',
    category: 'performance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_send_week',
    name: 'SEND WEEK — Trust the Process',
    description:
      'The training is done. Attempts only: 2-3 per session, 10+ min rest between. If the send does not happen, it does not happen — the beta is banked for next cycle. Immediately after the final attempt (send or not), complete the graduation assessment retest on the baselines.',
    duration: '60-90 min',
    focus: 'Send + Graduation',
    category: 'assessment',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
];
