import type { Drill } from '../types';

/** Drills sourced from The Long Game (12-Week Route & Endurance). */
export const LONG_GAME_DRILLS: Drill[] = [
  {
    id: 'tlg_arc_2x10',
    protocolId: 'arcing',
    timerOverride: { workSec: 600, sets: 2 },
    name: 'ARC Pacing — 2x10 min',
    duration: '30-45 min',
    focus: 'Aerobic Base',
    loads: ['sustained'],
    category: 'endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_arc_2x15',
    protocolId: 'arcing',
    timerOverride: { workSec: 900, sets: 2 },
    name: 'ARC Pacing — 2x15 min',
    duration: '45 min',
    focus: 'Aerobic Base + Shakeout',
    loads: ['sustained'],
    category: 'endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_arc_2x20',
    protocolId: 'arcing',
    timerOverride: { workSec: 1200, sets: 2 },
    name: 'ARC Pacing — 2x20 min',
    duration: '60 min',
    focus: 'Aerobic Base + Clipping',
    loads: ['sustained'],
    category: 'endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_deload_arc_movement',
    protocolId: 'arcing',
    timerOverride: { workSec: 720, sets: 2 },
    name: 'DELOAD: 2x12 min ARC + Movement Quality',
    duration: '30 min',
    focus: 'Recovery + Movement',
    loads: ['sustained'],
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_linked_laps_doubles',
    name: 'Linked Laps — Doubles',
    duration: '60-75 min',
    focus: 'Power Endurance',
    loads: ['sustained'],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_4x4_route_intervals',
    name: '4x4 Route Intervals',
    duration: '60-75 min',
    focus: 'Pump Tolerance',
    loads: ['forearm'],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_the_pump_clock',
    name: 'The Pump Clock',
    duration: '60 min',
    focus: 'Pump Management',
    loads: ['sustained'],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_deload_arc_2x10',
    protocolId: 'arcing',
    timerOverride: { workSec: 600, sets: 2 },
    name: 'DELOAD: 2x10 min ARC',
    duration: '30 min',
    focus: 'Recovery',
    loads: ['sustained', 'forearm'],
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_linked_laps_shakeout',
    name: 'Linked Laps 2 sets + Shakeout Drill',
    duration: '45-60 min',
    focus: 'Send-Week Prep',
    loads: [],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_maintenance_linked_laps',
    name: 'Maintenance Linked Laps',
    duration: '45-60 min',
    focus: 'Maintenance',
    loads: ['sustained'],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_arc_taper',
    protocolId: 'arcing',
    timerOverride: { workSec: 900, sets: 1 },
    name: 'ARC 1x15 min (Taper Week)',
    duration: '20 min',
    focus: 'Send Taper',
    loads: ['sustained'],
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_no_endurance_send_week',
    name: 'No Endurance — Send Week',
    duration: '0 min',
    focus: 'Send Week',
    loads: [],
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_onsight_route_reading',
    name: 'On-Sight Practice + Route Reading',
    duration: '60-90 min',
    focus: 'On-Sight Skill',
    loads: [],
    category: 'strategy',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_clipping_drills',
    name: 'Clipping Drills',
    duration: '60 min',
    focus: 'Clipping Efficiency',
    loads: [],
    category: 'technique',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_fall_ladder',
    name: 'Lead Fall Practice — The Fall Ladder',
    duration: '60 min',
    focus: 'Fall Training',
    loads: [],
    category: 'mental',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_deload_easy_onsights',
    name: 'DELOAD: 2-3 Easy On-Sights',
    duration: '45-60 min',
    focus: 'Recovery + Review',
    loads: [],
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_project_selection_burns',
    name: 'Project Selection — Working Burns',
    duration: '60-90 min',
    focus: 'Project Decoding',
    loads: [],
    category: 'strategy',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_crux_to_chains',
    name: 'Crux to Chains / Bottom to Crux',
    duration: '60-90 min',
    focus: 'Section Linking',
    loads: [],
    category: 'strategy',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_full_redpoint_attempts',
    name: 'Full Redpoint Attempts',
    duration: '60-90 min',
    focus: 'Full Redpoint',
    loads: [],
    category: 'performance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_deload_volume_day',
    name: 'DELOAD: Volume Day',
    duration: '60-90 min',
    focus: 'Recovery + Movement',
    loads: ['sustained'],
    category: 'recovery',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_visualization_burns',
    name: 'Visualization + Full Project Burns',
    duration: '75-90 min',
    focus: 'Send-Quality Burns',
    loads: [],
    category: 'performance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_film_review_projecting',
    name: 'Film + Review Projecting',
    duration: '75-90 min',
    focus: 'Technical Refinement',
    loads: ['hip'],
    category: 'strategy',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_peak_conditions_send',
    name: 'Peak Conditions Send Attempts',
    duration: '90 min',
    focus: 'Peak Send',
    loads: [],
    category: 'performance',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
  {
    id: 'tlg_send_week',
    name: 'SEND WEEK — Trust the Process',
    duration: '60-90 min',
    focus: 'Send + Graduation',
    loads: [],
    category: 'assessment',
    discipline: 'sport',
    level: '5.9-5.12',
    equipment: ['wall'],
    sources: ['the_long_game'],
  },
];
