import type { Drill } from '../types';

/** Drills sourced from Peak Performance (12-Week Advanced Boulder). */
export const PEAK_PERFORMANCE_DRILLS: Drill[] = [
  {
    id: 'pp_limit_four_burns',
    name: 'Limit Session — 4 Burns per Boulder',
    description:
      'Warm up 20-30 min to full temperature. Pick 3-4 projects at your max grade. 4 quality burns per project, 5 min rest between, 10+ min rest between projects. Stop if form visibly breaks on two consecutive burns — CNS is fried. Log attempts per project.',
    duration: '120 min',
    focus: 'Pure Limit Climbing',
    category: 'power',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_style_diverse_limit',
    name: 'Style-Diverse Limit Day',
    description:
      'Pick 3-4 projects that span different styles (slab, vertical, overhang, roof). Builds breadth at limit. 3-4 burns each, 5 min rest. Exposes weakest style — note which one felt worst, feed it into next Technique day.',
    duration: '120 min',
    focus: 'Style Breadth',
    category: 'power',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_crux_isolation',
    name: 'Crux Isolation',
    description:
      'Pick 2-3 projects where the crux move has been shutting you down. For each: try the crux in isolation (pre-rig the sequence) for 5-8 attempts with 3-4 min rest. THEN run the full boulder once. Isolation creates the strength gain; full run integrates it.',
    duration: '120 min',
    focus: 'Crux Skill',
    category: 'power',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_flow',
    name: 'DELOAD: Flow Session',
    description:
      'End of Build phase. Climb 45-60 min at RPE 6 on V5-V7. No limit work, no projects. Light session lets the fingers and CNS recover before Intensify. Sleep and eat well this week — tendon adaptation is happening in the background.',
    duration: '45-60 min',
    focus: 'Recovery',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_intensify_five_burns',
    name: 'Intensify Limit Block — 5 Burns',
    description:
      'Peak-volume limit session. Pick 3 projects, 5 quality burns each, 5 min rest between burns. This is the hardest climbing week of the program so far. If burn 5 feels worse than burn 1, stop the project — added fatigue is wasted.',
    duration: '150 min',
    focus: 'Peak Volume Limit',
    category: 'power',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_boulder_link_ups',
    name: 'Boulder Link-Ups',
    description:
      'Pick 2-3 moderate-to-hard problems (1-2 grades below max). Climb each TWICE back-to-back with no rest. 3 sets per problem with 5 min between sets. Builds power endurance at high intensity — your new max strength starts earning grades here.',
    duration: '120 min',
    focus: 'Power Endurance',
    category: 'power-endurance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_hard_flash_day',
    name: 'The Hard-Flash Day',
    description:
      'Warm up fully, then try to flash 5-6 boulders 1-2 grades below your max in a single session. No second burns allowed. Tests how well limit strength translates to first-go performance. Read sequences carefully before starting.',
    duration: '120 min',
    focus: 'Flash Performance',
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_flash_volume',
    name: 'DELOAD: Flash Volume',
    description:
      'End of Intensify. 20-25 moderate boulders (2-3 grades below max) with 1-2 min rest between. No limit work. Keeps motor patterns grooved while giving tendons and CNS a full week to catch up before Peak & Send.',
    duration: '90 min',
    focus: 'Recovery',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_critical_taper',
    name: 'DELOAD 2: The Critical Taper',
    description:
      'THIRTY-FIVE percent volume reduction. 4-5 boulders at moderate grade only. This second deload exists because tendons take MONTHS to adapt while muscles adapt in weeks. Muscles feel ready; tendons are not. Skip this week and your Peak sends become Peak injuries. Non-negotiable.',
    duration: '60 min',
    focus: 'Critical Recovery',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_peak_projecting',
    name: 'Peak Projecting — 6 Burns',
    description:
      'First peak session. Pick your #1 project. 6 burns with 6-8 min rest between — longer than normal because you are optimizing send quality, not accumulation. Visualize each sequence before leaving the ground. Note exactly where you fell and why.',
    duration: '150 min',
    focus: 'Send-Level Performance',
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_send_window',
    name: 'Send Window',
    description:
      'Pick your hardest project. 4-5 burns max, 8-10 min rest between. Sleep 8+ hrs night before. This is where the 12 weeks pay off. If the send does not happen this session, you have Week 12 — no panic.',
    duration: '120 min',
    focus: 'Send Performance',
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_graduation_retest',
    name: 'Graduation Retest & Final Send',
    description:
      'Split the week: one session to retest ALL baselines (Max Hang, Weighted Pull 3RM, Max Grade, Flash Grade, Front Lever, Hollow Body), one final send session on any remaining project. Log everything. Rest 3+ days after before any programming rotation.',
    duration: '60 + 120 min',
    focus: 'Assessment + Final Send',
    category: 'assessment',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['hangboard', 'wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_movement_inventory',
    name: 'Movement Inventory',
    description:
      'Climb 6-8 sub-max boulders while consciously inventorying your movement: where are feet slipping, which hands feel weak, which body positions feel awkward? Write 2-3 weaknesses in the notes. This phase is diagnostic — you are finding what to work on, not grinding a fix.',
    duration: '90 min',
    focus: 'Self-Analysis',
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_video_review_day',
    name: 'Video Review Day',
    description:
      'Film yourself on 4-5 boulders at 1-2 grades below max. Watch back between attempts. Look for: early arm-bend, hips drifting away from wall, foot placement hesitation. One focus per boulder. Video exposes what you cannot feel.',
    duration: '90 min',
    focus: 'External Feedback',
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_weakness_drilling_1',
    name: 'Targeted Weakness Drilling — Day 1',
    description:
      'Pick ONE weakness from Weeks 1-2. For that weakness, pick 4-5 sub-max boulders that expose it and climb each 2-3 times with deliberate attention. Example: weak compression means pinchy problems, climbed focusing purely on body tension. Rest 3 min between burns.',
    duration: '90 min',
    focus: 'Weakness Targeting',
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_weakness_drilling_2',
    name: 'Targeted Weakness Drilling — Day 2',
    description:
      'Pick your SECOND weakness and repeat the drilling structure from Week 3. Two weeks per weakness is the minimum dose for neural change to stick. If both weaknesses feel fixed already, pick a third.',
    duration: '90 min',
    focus: 'Weakness Targeting',
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_footwork_under_fatigue',
    name: 'Footwork Under Fatigue',
    description:
      'Climb 8-10 boulders 2-3 grades below max, with intentional small foot holds. Between boulders: 10 push-ups + 20s hollow body hold — pre-fatigue upper body and core. Simulates the footwork challenge on the last move of a project when you are pumped.',
    duration: '90 min',
    focus: 'Footwork Under Load',
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_silent_feet_hover',
    name: 'Silent Feet + Hover Hands',
    description:
      '6-8 moderate boulders (2 grades below max). Feet make no sound on holds, hands pause 2-3 seconds above next hold before placing. Slower session than you are used to. Forces precision under the mental tension that comes with the Intensify phase.',
    duration: '90 min',
    focus: 'Precision + Patience',
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_body_position_puzzles',
    name: 'Body Position Puzzles',
    description:
      'Pick 4-5 boulders that feature awkward or contested body positions (heel-toes, drop-knees, layback cruxes). Climb each 3 times, experimenting with subtle body position variations. Log which variation worked. Tactical flexibility.',
    duration: '90 min',
    focus: 'Body Position',
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_style_library',
    name: 'DELOAD: Style Library',
    description:
      'End of Intensify. Climb 10-15 V5-V7 boulders across ALL styles in one session. No projects. No focus. Just accumulate varied mileage on solid terrain. Gives the nervous system broad recovery while maintaining movement vocabulary.',
    duration: '75 min',
    focus: 'Recovery',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_integration_day',
    name: 'Integration Day',
    description:
      'After Deload 2. Climb 4-6 boulders at your old flash level — they should feel different. Apply Silent Feet and body position awareness from Phase 2. Every send should feel cleaner than it used to. Integration, not fixing more.',
    duration: '60 min',
    focus: 'Movement Integration',
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_flow_projecting_prep',
    name: 'Flow Projecting Prep',
    description:
      'Very low intensity, high volume. 15-20 boulders 3 grades below max. Climb them at speed (moderate RPE 5-6). Building motor-pattern speed for Peak week. Fewer mental cues, more fluid execution.',
    duration: '75 min',
    focus: 'Motor Pattern Speed',
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_light_maintenance',
    name: 'Light Maintenance',
    description:
      'Heart-rate-up, volume-low. 8-10 easy boulders. Goal is keeping the nervous system engaged without adding fatigue before send attempts. If you feel fresh, skip this session entirely and rest.',
    duration: '45 min',
    focus: 'CNS Maintenance',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_graduation_assessment',
    name: 'Graduation Assessment',
    description:
      'This week\'s technique session is the movement portion of your graduation assessment. Climb 5 different-style boulders at 1-2 grades below max. Rate attempt quality (0-10) independent of send/fail. Log anything that still feels weak — feeds into your next program pick.',
    duration: '60 min',
    focus: 'Assessment',
    category: 'assessment',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['hangboard', 'wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_project_selection',
    name: 'Project Selection',
    description:
      'Pick 1-2 projects at your max grade. For each: 5-6 attempts with 5-8 min rest between. Between attempts, visualize the next burn with eyes closed for 60 seconds minimum. Focus on move isolation — can you DO each move, not yet link them. Log exactly where you fell and why after every attempt.',
    duration: '150 min',
    focus: 'Move Isolation',
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_link_building',
    name: 'Link Building',
    description:
      'Same project(s) as Week 1. Now build links: start 2-3 moves before the crux, top out at 2-3 moves after. 5-6 attempts, 5-8 min rest. The goal is not the send — it is stringing consecutive moves. Do not try for the full redpoint yet.',
    duration: '150 min',
    focus: 'Link Building',
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_top_down_redpointing',
    name: 'Top-Down Redpointing',
    description:
      'Send the TOP section first. Start at the last rest before the top-out and climb through. Then extend down — start one move lower, send again. Builds ending-confidence for when you do try the full redpoint. 6-8 attempts, prioritize quality over count.',
    duration: '150 min',
    focus: 'Top-Down Strategy',
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_session_review',
    name: 'DELOAD: Session Review',
    description:
      'End of Build. Do not project this week. Use the session for low-intensity climbing (1-2 grades below project) AND to review all your crux notes from Weeks 1-3. Pick: do you keep this project for Intensify, or swap? Log your decision.',
    duration: '60 min',
    focus: 'Strategic Recovery',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_full_redpoint_attempts',
    name: 'Full Redpoint Attempts',
    description:
      'First full-boulder attempts. 5-6 burns with 6-8 min rest. Between burns, run the visualize-climb-note-rest loop. Before EVERY burn: eyes closed, run the full sequence in your head, 60s minimum. Notes after must be specific — not \'fell on the crux\' but \'left foot cut on the second-to-last move because I did not flag\'.',
    duration: '150 min',
    focus: 'Full Redpoint',
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_mental_game_commitment',
    name: 'Mental Game — Commitment',
    description:
      'If there is a scary move on your project (exposure, bad landing, dyno), this is the day. Use the isolation drill: do the scary move on a lower-stakes version until automatic. Then false starts: 2-3 attempts at full power, intentionally NOT grabbing. Proves the fall is safe. Then try for the send.',
    duration: '150 min',
    focus: 'Fear Management',
    category: 'mental',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_conditions_day',
    name: 'Conditions Day',
    description:
      'Time the session for peak conditions (cool, dry, low-crowd). Go for the send. 4-6 burns with 8-10 min rest — fewer but higher-quality attempts. If no send, log exactly what happened: fell on X move because Y. Feeds into Deload 2 strategy.',
    duration: '150 min',
    focus: 'Peak Conditions Send Attempt',
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_strategy_review',
    name: 'DELOAD: Strategy Review',
    description:
      'End of Intensify. No projecting. Low-intensity climbing plus an honest review of project progress. Decide: double down on this project for Peak (if links are consistent), or switch to a different project at the same grade. Overcommitting to a plateau project is how send cycles fail.',
    duration: '60 min',
    focus: 'Strategic Recovery',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload2_light_session',
    name: 'DELOAD 2: Light Session',
    description:
      'Second tendon-recovery week. NO projecting. Short, easy session only — moderate boulders, 1-2 grades below max. The project is waiting; your tendons are catching up. One week of restraint here saves three weeks of injury.',
    duration: '60 min',
    focus: 'Critical Recovery',
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_peak_session_1',
    name: 'Peak Session 1',
    description:
      'Peak phase projecting. 6-8 burns on your chosen project with 8-10 min rest. Decoupling: RATE each attempt 0-10 on execution quality independent of send/fail. A perfect attempt that falls is a better stimulus than a sloppy send. Focus on flow — challenge-skill balance, clear goals, immediate feedback.',
    duration: '150 min',
    focus: 'Peak Performance',
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_send_attempts_quality',
    name: 'Send Attempts — Quality Window',
    description:
      '4-6 burns max, 10-15 min rest between. Prioritize SEND quality. Sleep 8+ hrs the night before. Warm up 40 min, not 30. The ceiling for the 12 weeks — express everything you built. If no send, the send window continues into Week 12.',
    duration: '150 min',
    focus: 'Send Quality',
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_final_attempts',
    name: 'Final Attempts + Assessment',
    description:
      'Either send the project (celebrate), or bank the beta and graduate. Either way, complete the assessment retest in your other session this week. Then take 3+ full rest days before any new program. Rotating programs while running on fumes from a Peak cycle compounds into injury.',
    duration: '120 min',
    focus: 'Send + Graduation',
    category: 'assessment',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['hangboard', 'wall'],
    sources: ['peak_performance'],
  },
];
