import type { Drill } from '../types';

/** Drills sourced from Peak Performance (12-Week Advanced Boulder). */
export const PEAK_PERFORMANCE_DRILLS: Drill[] = [
  {
    id: 'pp_limit_four_burns',
    name: 'Limit Session — 4 Burns per Boulder',
    duration: '120 min',
    focus: 'Pure Limit Climbing',
    loads: [],
    category: 'power',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_style_diverse_limit',
    name: 'Style-Diverse Limit Day',
    duration: '120 min',
    focus: 'Style Breadth',
    loads: [],
    category: 'power',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_crux_isolation',
    name: 'Crux Isolation',
    duration: '120 min',
    focus: 'Crux Skill',
    loads: [],
    category: 'power',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_flow',
    name: 'DELOAD: Flow Session',
    duration: '45-60 min',
    focus: 'Recovery',
    loads: [],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_intensify_five_burns',
    name: 'Intensify Limit Block — 5 Burns',
    duration: '150 min',
    focus: 'Peak Volume Limit',
    loads: [],
    category: 'power',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_boulder_link_ups',
    name: 'Boulder Link-Ups',
    duration: '120 min',
    focus: 'Power Endurance',
    loads: [],
    category: 'power-endurance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_hard_flash_day',
    name: 'The Hard-Flash Day',
    duration: '120 min',
    focus: 'Flash Performance',
    loads: [],
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_flash_volume',
    name: 'DELOAD: Flash Volume',
    duration: '90 min',
    focus: 'Recovery',
    loads: [],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_critical_taper',
    name: 'DELOAD 2: The Critical Taper',
    duration: '60 min',
    focus: 'Critical Recovery',
    loads: [],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_peak_projecting',
    name: 'Peak Projecting — 6 Burns',
    duration: '150 min',
    focus: 'Send-Level Performance',
    loads: [],
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_send_window',
    name: 'Send Window',
    duration: '120 min',
    focus: 'Send Performance',
    loads: [],
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_graduation_retest',
    name: 'Graduation Retest & Final Send',
    duration: '60 + 120 min',
    focus: 'Assessment + Final Send',
    loads: ['fingers', 'lever', 'hip', 'core'],
    category: 'assessment',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['hangboard', 'wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_movement_inventory',
    name: 'Movement Inventory',
    duration: '90 min',
    focus: 'Self-Analysis',
    loads: [],
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_video_review_day',
    name: 'Video Review Day',
    duration: '90 min',
    focus: 'External Feedback',
    loads: ['hip'],
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_weakness_drilling_1',
    name: 'Targeted Weakness Drilling — Day 1',
    duration: '90 min',
    focus: 'Weakness Targeting',
    loads: ['open-hand', 'shoulder'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_weakness_drilling_2',
    name: 'Targeted Weakness Drilling — Day 2',
    duration: '90 min',
    focus: 'Weakness Targeting',
    loads: [],
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_footwork_under_fatigue',
    name: 'Footwork Under Fatigue',
    duration: '90 min',
    focus: 'Footwork Under Load',
    loads: ['shoulder', 'core'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_silent_feet_hover',
    name: 'Silent Feet + Hover Hands',
    duration: '90 min',
    focus: 'Precision + Patience',
    loads: [],
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_body_position_puzzles',
    name: 'Body Position Puzzles',
    duration: '90 min',
    focus: 'Body Position',
    loads: ['legs'],
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_style_library',
    name: 'DELOAD: Style Library',
    duration: '75 min',
    focus: 'Recovery',
    loads: [],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_integration_day',
    name: 'Integration Day',
    duration: '60 min',
    focus: 'Movement Integration',
    loads: [],
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_flow_projecting_prep',
    name: 'Flow Projecting Prep',
    duration: '75 min',
    focus: 'Motor Pattern Speed',
    loads: [],
    category: 'technique',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_light_maintenance',
    name: 'Light Maintenance',
    duration: '45 min',
    focus: 'CNS Maintenance',
    loads: [],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_graduation_assessment',
    name: 'Graduation Assessment',
    duration: '60 min',
    focus: 'Assessment',
    loads: [],
    category: 'assessment',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_project_selection',
    name: 'Project Selection',
    duration: '150 min',
    focus: 'Move Isolation',
    loads: [],
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_link_building',
    name: 'Link Building',
    duration: '150 min',
    focus: 'Link Building',
    loads: [],
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_top_down_redpointing',
    name: 'Top-Down Redpointing',
    duration: '150 min',
    focus: 'Top-Down Strategy',
    loads: [],
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_session_review',
    name: 'DELOAD: Session Review',
    duration: '60 min',
    focus: 'Strategic Recovery',
    loads: [],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_full_redpoint_attempts',
    name: 'Full Redpoint Attempts',
    duration: '150 min',
    focus: 'Full Redpoint',
    loads: ['hook'],
    category: 'strategy',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_mental_game_commitment',
    name: 'Mental Game — Commitment',
    duration: '150 min',
    focus: 'Fear Management',
    loads: ['dynamic', 'legs'],
    category: 'mental',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_conditions_day',
    name: 'Conditions Day',
    duration: '150 min',
    focus: 'Peak Conditions Send Attempt',
    loads: ['shoulder'],
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload_strategy_review',
    name: 'DELOAD: Strategy Review',
    duration: '60 min',
    focus: 'Strategic Recovery',
    loads: [],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_deload2_light_session',
    name: 'DELOAD 2: Light Session',
    duration: '60 min',
    focus: 'Critical Recovery',
    loads: [],
    category: 'recovery',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_peak_session_1',
    name: 'Peak Session 1',
    duration: '150 min',
    focus: 'Peak Performance',
    loads: [],
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_send_attempts_quality',
    name: 'Send Attempts — Quality Window',
    duration: '150 min',
    focus: 'Send Quality',
    loads: ['shoulder'],
    category: 'performance',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
  {
    id: 'pp_final_attempts',
    name: 'Final Attempts + Assessment',
    duration: '120 min',
    focus: 'Send + Graduation',
    loads: [],
    category: 'assessment',
    discipline: 'boulder',
    level: 'V8-V11',
    equipment: ['wall'],
    sources: ['peak_performance'],
  },
];
