import type { Drill } from '../types';

/** Drills sourced from The Siege (12-Week Advanced Sport). */
export const SIEGE_DRILLS: Drill[] = [
  {
    id: 'sg_project_selection_recon',
    name: 'Project Selection & Recon',
    duration: '90-120 min',
    focus: 'Project Selection',
    loads: [],
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_move_by_move_decoding',
    name: 'Move-By-Move Decoding',
    duration: '90-120 min',
    focus: 'Crux Decoding',
    loads: [],
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_beta_refinement_rests',
    name: 'Beta Refinement & Rests',
    duration: '90-120 min',
    focus: 'Beta Refinement',
    loads: ['campus'],
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_first_links_checkpoint',
    name: 'First Links + Checkpoint',
    duration: '90-120 min',
    focus: 'Early Links & Assessment',
    loads: ['fingers'],
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_section_links_doubles',
    name: 'Section Links — Doubles',
    duration: '90-120 min',
    focus: 'Section Linking',
    loads: [],
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_extend_links_crux',
    name: 'Extend Links Through the Crux',
    duration: '90-120 min',
    focus: 'Crux Linking',
    loads: ['sustained', 'forearm'],
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_bottom_to_crux',
    name: 'Bottom-to-Crux / Crux-to-Chains',
    duration: '90-120 min',
    focus: 'Half-Route Links',
    loads: [],
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_longest_links_reassess',
    name: 'Longest Links + Reassess',
    duration: '90-120 min',
    focus: 'Link Consolidation',
    loads: [],
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_full_redpoint_burns',
    name: 'Full Redpoint Burns',
    duration: '90-120 min',
    focus: 'Redpoint Burns',
    loads: [],
    category: 'performance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_first_one_hang',
    name: 'First One-Hang',
    duration: '90-120 min',
    focus: 'One-Hang Attempts',
    loads: ['hip'],
    category: 'performance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_refine_dont_rehearse',
    name: 'Refine, Don\'t Rehearse',
    duration: '90-120 min',
    focus: 'Send Optimization',
    loads: [],
    category: 'performance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_send_window',
    name: 'Send Window',
    duration: '90-120 min',
    focus: 'Send Execution',
    loads: [],
    category: 'performance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_capacity_laps_arc',
    timerOverride: { workSec: 900, sets: 2 },
    name: 'Capacity Laps (ARC)',
    protocolId: 'arcing',
    duration: '45-60 min',
    focus: 'Aerobic Capacity',
    loads: ['sustained', 'forearm'],
    category: 'endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_arc_volume_build',
    timerOverride: { workSec: 1080, sets: 2 },
    name: 'ARC Volume Build',
    protocolId: 'arcing',
    duration: '45-60 min',
    focus: 'Aerobic Capacity',
    loads: ['sustained'],
    category: 'endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_arc_light_intervals',
    timerOverride: { workSec: 900, sets: 1 },
    name: 'ARC + Light Intervals',
    protocolId: 'arcing',
    duration: '50-65 min',
    focus: 'Capacity + Intervals',
    loads: ['sustained'],
    category: 'endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_capacity_consolidation',
    timerOverride: { workSec: 1200, sets: 2 },
    name: 'Capacity Consolidation',
    protocolId: 'arcing',
    duration: '45-60 min',
    focus: 'Aerobic Base',
    loads: ['sustained'],
    category: 'endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_rope_links_doubles',
    name: 'Rope Links — Doubles',
    duration: '60-75 min',
    focus: 'Power-Endurance',
    loads: ['sustained', 'forearm', 'core'],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_doubles_added_volume',
    name: 'Doubles — Added Volume',
    duration: '60-75 min',
    focus: 'Power-Endurance',
    loads: ['sustained', 'forearm', 'legs'],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_rope_links_triples',
    name: 'Rope Links — Triples',
    duration: '60-75 min',
    focus: 'Sustained Power-Endurance',
    loads: [],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_triples_peak_volume',
    name: 'Triples — Peak Volume',
    duration: '60-75 min',
    focus: 'Peak Power-Endurance',
    loads: ['sustained', 'legs'],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_redpoint_bursts',
    name: 'Redpoint-Specificity Bursts',
    duration: '60-75 min',
    focus: 'Burst Recovery',
    loads: ['sustained'],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_burst_intensity',
    name: 'Burst Intensity',
    duration: '60-75 min',
    focus: 'Peak Bursts',
    loads: [],
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_taper_begins',
    name: 'Taper Begins',
    duration: '45-60 min',
    focus: 'Taper',
    loads: [],
    category: 'recovery',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_send_support',
    timerOverride: { workSec: 600, sets: 1 },
    name: 'Send Support',
    protocolId: 'arcing',
    duration: '30-45 min',
    focus: 'Maintenance',
    loads: ['sustained', 'forearm'],
    category: 'recovery',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
];
