import type { Drill } from '../types';

/** Drills sourced from The Siege (12-Week Advanced Sport). */
export const SIEGE_DRILLS: Drill[] = [
  {
    id: 'sg_project_selection_recon',
    name: 'Project Selection & Recon',
    description:
      'Try 2-3 candidate routes 1-2 grades above your current redpoint. Climb each on top-rope or with a stick-clip — you are auditioning, not sending. Pick THE project by the end of the session. Selection rule: if you can do every move first try, it is too easy; if you cannot decode the crux at all, it is too hard. The right project has a clear crux you can imagine unlocking and a few sections you already climb cleanly.',
    duration: '90-120 min',
    focus: 'Project Selection',
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_move_by_move_decoding',
    name: 'Move-By-Move Decoding',
    description:
      'Work the project one move at a time, using stick-clip or top-rope as needed. Figure out the beta for each individual move and rehearse it until it feels repeatable. Do not care about linking yet — care about knowing exactly what every move demands. Expect 4-6 focused attempts with 8-15 min rest between. Log the moves that feel low-percentage.',
    duration: '90-120 min',
    focus: 'Crux Decoding',
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_beta_refinement_rests',
    name: 'Beta Refinement & Rests',
    description:
      'Refine the sequence you decoded. Hunt micro-beta — a thumb catch, a heel that turns a campus into a reach, a knee bar that becomes a rest. Find and rehearse every shake-out and stance on the route. Test alternative beta through the crux: the first solution is rarely the most efficient. By the end of this session your beta should feel close to final.',
    duration: '90-120 min',
    focus: 'Beta Refinement',
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_first_links_checkpoint',
    name: 'First Links + Checkpoint',
    description:
      'Start chaining: link 3-5 move sections, including at least one attempt through the crux. Keep the volume moderate — your fingerboard work deloads this week, so respect the recovery. Checkpoint: if the moves still feel impossible rather than low-percentage, reassess your project choice now, before you invest the linking phase in it.',
    duration: '90-120 min',
    focus: 'Early Links & Assessment',
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_section_links_doubles',
    name: 'Section Links — Doubles',
    description:
      'Link 5-8 move sections, especially through and around the crux. 2-3 quality burns per session with 15-20 min rest between — each burn should be a genuine effort, not a rehearsal. Climb in the better conditions of your session window. The goal this week: stitch the route into 3-4 reliable chunks.',
    duration: '90-120 min',
    focus: 'Section Linking',
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_extend_links_crux',
    name: 'Extend Links Through the Crux',
    description:
      'Chain longer. At least one link this session should carry from before the crux to after it — the crux move executed with pump in the forearms, not fresh. 2-3 burns, 15-20 min rest. If you can only do the crux fresh but never linked into it, that is the exact capacity the Power-Endurance session is building in parallel.',
    duration: '90-120 min',
    focus: 'Crux Linking',
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_bottom_to_crux',
    name: 'Bottom-to-Crux / Crux-to-Chains',
    description:
      'On your best burn of the day, link from the ground all the way to the crux, OR from the crux to the anchors. Pick whichever half is your weakness. 2-3 high-quality burns with 15-20 min rest. You are proving you can arrive at the crux with enough left to fight, and finish the route once past it.',
    duration: '90-120 min',
    focus: 'Half-Route Links',
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_longest_links_reassess',
    name: 'Longest Links + Reassess',
    description:
      'Link the biggest chunks the route allows — ideally ground-to-crux-to-near-the-chains in one or two pieces. Reassessment rule: if you are still falling BEFORE the crux this week, the route may be too hard for this cycle — consider dropping a grade so you get a send under your belt. By the end of Week 8 you should have at least one link that includes the full crux sequence.',
    duration: '90-120 min',
    focus: 'Link Consolidation',
    category: 'strategy',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_full_redpoint_burns',
    name: 'Full Redpoint Burns',
    description:
      'Switch to single-attempt mode. 2-3 full redpoint burns from the ground with 20-30 min rest between. Conditions matter now — climb in the coolest, driest part of your session. Warm up thoroughly but conserve skin and fingers for the real attempts. Treat every burn as a send attempt: same warm-up, same focus, same clipping.',
    duration: '90-120 min',
    focus: 'Redpoint Burns',
    category: 'performance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_first_one_hang',
    name: 'First One-Hang',
    description:
      'Aim for a one-hang: the whole route with a single rest or fall. This is the last milestone before the send and a strong predictor it is coming. 2 maybe 3 burns, full rest between, best conditions. Protect skin aggressively — tape splits early, and stop the session while your fingers still feel crisp.',
    duration: '90-120 min',
    focus: 'One-Hang Attempts',
    category: 'performance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_refine_dont_rehearse',
    name: 'Refine, Don\'t Rehearse',
    description:
      'You know the route — now optimize the variables around it. Dial clipping stances, the exact warm-up that leaves you primed but not pumped, and the time-of-day with the best conditions. Reduce volume so every burn is fully fresh. You are no longer learning moves; you are removing reasons to fall.',
    duration: '90-120 min',
    focus: 'Send Optimization',
    category: 'performance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_send_window',
    name: 'Send Window',
    description:
      'Taper hard. Keep attempts few and fully rested — quality over quantity. Maximize recovery between burns (30+ min) and prioritize the coolest, driest window of the day. If conditions are poor, it is fine to wait for a better day rather than burn skin on a low-percentage go. This is the send.',
    duration: '90-120 min',
    focus: 'Send Execution',
    category: 'performance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_capacity_laps_arc',
    name: 'Capacity Laps (ARC)',
    description:
      'Aerobic Restoration and Capillarization. Continuous climbing at RPE 3-4 (easy breathing, mild pump) on easy routes or long traverses. 15-20 min continuous, 2 rounds with 5 min rest between. Do not stop between routes — keep moving. This is boring and foundational; it grows the capillary network your forearms use to clear pump. Skip it and the linking weeks will hurt more.',
    protocolId: 'arcing',
    duration: '45-60 min',
    focus: 'Aerobic Capacity',
    category: 'endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_arc_volume_build',
    name: 'ARC Volume Build',
    description:
      'Same aerobic intent, more time under tension. Extend to 18-22 min continuous, 2-3 rounds, 5 min rest between. Stay strictly at RPE 3-4 — if you get genuinely pumped you are climbing too hard and training the wrong system. Use easier terrain or bigger holds to keep moving the whole round.',
    protocolId: 'arcing',
    duration: '45-60 min',
    focus: 'Aerobic Capacity',
    category: 'endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_arc_light_intervals',
    name: 'ARC + Light Intervals',
    description:
      'Bridge toward links. One ARC round (15-20 min easy continuous), then 2-3 light interval laps: climb 2-3 minutes at RPE 5-6, rest an equal amount, repeat. This introduces a moderate pump-and-clear cycle without the intensity of true doubles. Keep form clean — sloppy intervals just teach bad movement under fatigue.',
    protocolId: 'arcing',
    duration: '50-65 min',
    focus: 'Capacity + Intervals',
    category: 'endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_capacity_consolidation',
    name: 'Capacity Consolidation',
    description:
      'Your last pure-base week before the linking block. Peak the ARC volume: 2-3 long rounds (20+ min) at RPE 3-4, or one extended pyramid. Keep it easy and high-volume — you are banking aerobic capacity, not testing it. Next week the intensity steps up, so finish this session pump-free and recovered.',
    protocolId: 'arcing',
    duration: '45-60 min',
    focus: 'Aerobic Base',
    category: 'endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_rope_links_doubles',
    name: 'Rope Links — Doubles',
    description:
      'Pick 2 routes at 80-90% of your redpoint grade. Climb the first, lower, and pull straight back onto the second — no ground rest. Rest 4-6 min between sets and repeat 3-4 times. This is the core power-endurance stimulus: teaching the forearms to keep working and partially recover through sustained pump.',
    duration: '60-75 min',
    focus: 'Power-Endurance',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_doubles_added_volume',
    name: 'Doubles — Added Volume',
    description:
      'Same doubles format, slightly more load: add a set (4-5 total) or nudge route difficulty toward 90% of redpoint. Rest 4-6 min between sets. The target is buffering pump on harder terrain — by the end of the set your forearms should be deeply pumped but your movement still controlled. If form collapses, drop intensity, not focus.',
    duration: '60-75 min',
    focus: 'Power-Endurance',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_rope_links_triples',
    name: 'Rope Links — Triples',
    description:
      'Upgrade to triples: 3 routes back-to-back with no ground rest, 5-7 min between sets, 2-3 sets total. Use routes around 80% of redpoint so you can complete all three. Triples push the duration of the pumped state and rehearse recovering between crux sections — exactly what a long project demands.',
    duration: '60-75 min',
    focus: 'Sustained Power-Endurance',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_triples_peak_volume',
    name: 'Triples — Peak Volume',
    description:
      'The highest power-endurance volume of the program: 3-4 sets of triples, 5-7 min between. This is the peak of the linking block — next week shifts toward send-specific intensity. Quality rule: if your climbing turns to flailing, drop a route rather than grind out junk laps. Pumped-but-precise beats exhausted-and-sloppy.',
    duration: '60-75 min',
    focus: 'Peak Power-Endurance',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_redpoint_bursts',
    name: 'Redpoint-Specificity Bursts',
    description:
      'Shift from volume to intensity. Pick a route at your redpoint grade (not your project). 1 all-out burn, 20 min full rest, then 1-2 more. This mimics the pattern of actual send-day projecting so your body rehearses the recovery-to-peak cycle. Each burn is maximal effort followed by real recovery — not a circuit.',
    duration: '60-75 min',
    focus: 'Burst Recovery',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_burst_intensity',
    name: 'Burst Intensity',
    description:
      'Peak burst week. 1-2 maximal burns on a redpoint-grade route with full recovery (20+ min) between. The system you want on send day is the ability to go to your limit, recover, and go again — rehearse exactly that. Keep total volume low; intensity is the whole point and fatigue is the enemy.',
    duration: '60-75 min',
    focus: 'Peak Bursts',
    category: 'power-endurance',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_taper_begins',
    name: 'Taper Begins',
    description:
      'Cut volume in half and hold intensity. One or two crisp bursts on a redpoint-grade route, full rest, then stop. You are keeping the power-endurance system sharp while shedding accumulated fatigue so it is available for the project. Leave the session feeling like you could have done more.',
    duration: '45-60 min',
    focus: 'Taper',
    category: 'recovery',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
  {
    id: 'sg_send_support',
    name: 'Send Support',
    description:
      'Minimal volume — just enough to stay primed. A short ARC flush (10-15 min easy continuous) or one easy burst to keep the forearms awake without adding fatigue. Skip this session entirely if you are deep in send attempts on the project; recovery for the redpoint takes priority over any training stimulus this week.',
    protocolId: 'arcing',
    duration: '30-45 min',
    focus: 'Maintenance',
    category: 'recovery',
    discipline: 'sport',
    level: '5.12d-5.13d',
    equipment: ['wall'],
    sources: ['the_siege'],
  },
];
