import type { Guide } from './types';

export const NEW_TO_CLIMBING: Guide = {
  id: 'new_to_climbing',
  name: 'New to Climbing',
  subtitle: 'What to know before your first session, and what to do on the day.',
  sections: [
    {
      title: 'Climbing 101: Start Here',
      content: [
        { kind: 'p', text: '**New to climbing?** This section covers what you actually need to know before your first session. About 10 minutes to read; reference it anytime.' },
        { kind: 'note', text: 'Written for someone who has not climbed before, or has been a handful of times. Nothing in it depends on the app — come back to it whenever.' },
        { kind: 'h', text: 'What climbing is' },
        { kind: 'p', text: 'Climbing is moving up rock or plastic. Most people start indoors. The main disciplines:' },
        { kind: 'list', items: [
          '**Bouldering** — short climbs over a padded floor, no ropes. Indoor problems are usually 10-15 feet tall. This is where most people start.',
          '**Top-rope** — taller routes (30-60 feet indoors) with a rope already running through an anchor at the top. The rope catches you immediately if you fall. Safest entry to roped climbing.',
          '**Sport (lead)** — same height as top-rope, but you clip the rope into bolts as you climb. Falls go further. Done after you\'ve spent time on top-rope.',
          '**Trad** — placing your own protection (cams, nuts) into rock cracks instead of clipping pre-installed bolts. Outdoor only, advanced.',
        ] },
        { kind: 'p', text: 'Most beginners stick to bouldering or top-rope for the first year. Both are cheap to start: a gym day pass and rental shoes get you climbing the same day. You don\'t need to pick one — many climbers do both.' },
        { kind: 'h', text: 'Grades explained' },
        { kind: 'p', text: 'Climbing routes get graded by difficulty. There are two systems you\'ll see in the US:' },
        { kind: 'list', items: [
          '**V-scale** (for bouldering) — runs from V0 (easiest) upward. V0-V2 is beginner range. V3-V5 is intermediate. V6+ is advanced. The hardest established problem in the world is V17.',
          '**YDS** (Yosemite Decimal System, for rope climbing) — runs 5.0 to 5.15+. Beginners climb 5.5 to 5.9. Intermediate is 5.10 (often split into 5.10a, b, c, d). Advanced climbers project 5.12+.',
        ] },
        { kind: 'p', text: 'Grades are not exact — they vary between gyms and especially between gym and outdoor climbing (outdoors usually feels harder for the same number). The grade just describes how a particular climb feels to most climbers.' },
        { kind: 'p', text: 'Your first goal: stop caring about the grade. Try whatever looks fun. You\'ll improve faster by attempting harder things you can\'t do than by repeating easy things you can.' },
        { kind: 'h', text: 'What you actually need' },
        { kind: 'p', text: 'For your first six months of climbing, you can get by with very little:' },
        { kind: 'list', items: [
          '**Rental shoes** — every gym rents them. $5-10 per visit. They\'re not great, but they\'ll do. Wait a month or two before buying your own.',
          '**Chalk** — dries sweat on your fingers for grip. Small bags cost a few bucks; a chalk ball ($10) lasts months.',
          '**Comfortable clothing** — anything you can move in. Stretchy pants and a t-shirt are fine. Climbing-specific pants are nice but not necessary.',
        ] },
        { kind: 'p', text: 'For roped climbing (top-rope or lead), you\'ll also need a harness ($60-80) and a climbing partner. Gyms usually have a belay class that teaches you to manage the rope — most gyms require you to pass it before climbing with ropes.' },
        { kind: 'note', text: 'Don\'t buy a hangboard or fingerboard for at least 6 months. They wreck inexperienced fingers. Climb on actual rock or plastic first.' },
        { kind: 'h', text: 'Climbing vocabulary' },
        { kind: 'p', text: 'You\'ll hear these constantly:' },
        { kind: 'list', items: [
          '**Send** — to complete a climb cleanly, from bottom to top without falling.',
          '**Flash** — to send a climb on your first try, with no prior knowledge of the moves.',
          '**Onsight** — like a flash, but with zero prior information (no watching others, no beta beforehand). Roped climbing term.',
          '**Redpoint** — to send a climb after previously attempting it. The most common type of send for harder climbs.',
          '**Project** — a climb you can\'t do yet, but are working on. Could take days, weeks, or years.',
          '**Beta** — information about how to do a climb. "Got any beta?" means "tell me how to do this."',
          '**Crux** — the hardest single move or short section of a climb. Every climb has one. If you fall, it\'s usually here.',
          '**Slab** — a wall angled less than vertical (you can stand on the holds). Easier physically, hard mentally — feels like the ground tilted away.',
          '**Vertical** — a wall at 90°. Most beginner-friendly.',
          '**Overhang** — a wall past vertical. Hard on grip and core. Most boulders feature some overhang.',
        ] },
        { kind: 'h', text: 'Reading a route' },
        { kind: 'p', text: 'Every climb has a sequence — the specific order and way you grab each hold and put each foot. Figuring out the sequence is called **reading the route**.' },
        { kind: 'p', text: 'Before you start climbing, look at the route from the ground. Identify:' },
        { kind: 'list', items: [
          '**Where it starts** — usually a marked hold (look for a sticker or tape with the route\'s grade).',
          '**Where it ends** — the top hold. Sometimes marked, sometimes obvious.',
          '**The big holds** — these are likely the moves you\'ll set up from. Smaller holds in between are setup moves.',
          '**The crux** — guess where the climb might be hardest. Often where the holds get smaller, the wall steeper, or the moves longer.',
        ] },
        { kind: 'p', text: 'On the wall, your body position matters as much as your grip. A few principles:' },
        { kind: 'list', items: [
          'Keep your hips close to the wall when holds are positive (easy to grip).',
          'Drop your hip toward the wall when reaching with the same-side hand (called a "drop knee").',
          'Use your feet. New climbers grip too hard with their hands; experienced climbers stand on their feet and let their hands just steer.',
        ] },
        { kind: 'p', text: 'You\'ll fail at sequences and learn from each failure. That\'s the entire sport.' },
      ],
    },
    {
      title: 'Your First Day at the Gym',
      content: [
        { kind: 'p', text: '**Reading is one thing, doing is another.** Here\'s the literal step-by-step for your first visit to a climbing gym. Total time: about 1.5-2 hours including travel. Cost: $20-$35 for the day.' },
        { kind: 'note', text: 'This walkthrough is for bouldering — the simplest entry format. No partner, no rope, no certification needed. Just shoes and chalk.' },
        { kind: 'h', text: 'Before you go' },
        { kind: 'list', items: [
          '**Find a gym.** Search \'bouldering gym near me\' or \'climbing gym near me\' in Maps. Most cities have at least one. Check the website for first-timer info and whether they require any kind of orientation.',
          '**Bring:** athletic clothes you can move in, a water bottle, a snack. That\'s the entire kit.',
          '**Call ahead if:** the gym is mixed (bouldering + ropes) and you can\'t tell whether you need a partner. Pure bouldering gyms never require one.',
        ] },
        { kind: 'h', text: 'Arriving at the gym' },
        { kind: 'list', items: [
          '**1. Day pass + rentals.** Tell the front desk it\'s your first time. They\'ll have you sign a waiver and may offer a quick 5-minute safety briefing — take it. Day pass: $15-25. Shoe rental: $5-7. Chalk: $2-3.',
          '**2. Change and stash your stuff.** Climbing shoes go on bare feet (or thin socks if you\'d rather). They\'ll feel tight — that\'s normal. Only wear them while climbing; take them off between climbs.',
          '**3. Walk around for 5 minutes.** Look at the walls. Each colored tape or hold-set is a different problem (route). Find the easiest grade — usually V0 or VB — and remember where it is.',
        ] },
        { kind: 'h', text: 'Warming up' },
        { kind: 'list', items: [
          '**4. Easy movement first.** Arm circles, leg swings, light jumping jacks. 3-5 minutes. Cold tendons get hurt; warm tendons don\'t.',
          '**5. Easy traversing.** Move sideways across the wall on big easy holds, staying low. 2-3 minutes. Don\'t go up — the goal is to get blood into your forearms before anything hard.',
        ] },
        { kind: 'h', text: 'Your first climbs' },
        { kind: 'list', items: [
          '**6. Pick a V0 or VB.** Easiest grade. Stand at the start (sometimes marked with a sign) and look up at the holds you can reach. Plan a couple of moves before committing.',
          '**7. Climb slowly.** Focus on your feet. Push with your legs, not your arms. Most beginners over-grip and burn out their forearms in 10 minutes — you don\'t have to.',
          '**8. Top out or down-climb.** When you reach the final hold and hold it with both hands for a moment, you\'ve sent the problem. Down-climb if you can; jumping down is fine but harder on knees over time.',
          '**9. Rest 2-3 minutes between attempts.** Sit on a bench. Watch other climbers — you\'ll learn a ton from observation. Hydrate.',
        ] },
        { kind: 'h', text: 'Wrapping up' },
        { kind: 'list', items: [
          '**10. Try 3-5 different problems.** A few at V0, maybe one slightly harder if it looks fun. Don\'t grind one problem to exhaustion on day one.',
          '**11. Stop before you\'re trashed.** When your forearms feel pumped and your grip is failing, you\'re done. First-session climbing time: 45-60 minutes of actual climbing max.',
          '**12. Cool down.** Light stretches for shoulders, forearms, and hips. 3-5 minutes. Skip ballistic stretching.',
          '**13. Log your session in Project Ascent.** Tap Log → Bouldering → mark the V0s you sent. The First Climb quest auto-completes.',
        ] },
        { kind: 'note', text: '**Expect to be sore.** Forearms, fingers, back, shoulders. That\'s normal. Take 1-2 rest days before your next session — climbing soreness usually peaks 24-48 hours after.' },
      ],
    },
  ],
};
